<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (resultado*)>
<!ELEMENT resultado (local, visitante, golesL, golesV)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT golesL (#PCDATA)>
<!ELEMENT golesV (#PCDATA)>
]>

<resultados>
    <resultado>
        <local>Nottingham Presa</local>
        <visitante>Inter de Mitente</visitante>
        <golesL>0</golesL>
        <golesV>1</golesV>
    </resultado>
    <resultado>
        <local>Vodka Juniors</local>
        <visitante>Sparta da Risa</visitante>
        <golesL>3</golesL>
        <golesV>3</golesV>
    </resultado>
    <resultado>
        <local>Water de Munich</local>
        <visitante>Esteaua es del grifo</visitante>
        <golesL>4</golesL>
        <golesV>2</golesV>
    </resultado>
</resultados>