<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv[
<!ELEMENT cv (presentacion, (datos_academicos | experiencia_laboral)+,
(lectura|deportes|otros)*, referencias*)>
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT datos_academicos (#PCDATA)>
<!ELEMENT experiencia_laboral (#PCDATA)>
<!ELEMENT lectura (#PCDATA)>
<!ELEMENT deportes (#PCDATA)>
<!ELEMENT otros (#PCDATA)>
<!ELEMENT referencias (#PCDATA)>
]>

<cv>
    <presentacion>Buenas tardes</presentacion>
    <experiencia_laboral>3 años de experiencia en el sector</experiencia_laboral>
    <datos_academicos>Ingeniería Mecánica</datos_academicos>
    <deportes>Natación</deportes>
    <referencias>Empresa X</referencias>
    <referencias>Empresa Y</referencias>
</cv>
