<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda[
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf)>
<!ATTLIST persona id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
]>
<agenda>
    <persona id="01">
        <nombre>Ricardo Borriquero</nombre>
        <tlf>951345678</tlf>
    </persona>
    <persona id="02">
        <nombre>Eva Risto</nombre>
        <tlf>955837659</tlf>
    </persona>
</agenda>
