=== ibq-daw1-1920-27/lmsgi/Unidad_04/Actividad_04_04/Ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" minOccurs="1" maxOccurs="30">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"  type="xs:string"/>
                            <xs:element name="apellidos" type="xs:string"/>
                            <xs:element name="nota">
                                <xs:simpleType>
                                    <xs:union>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                                <xs:minInclusive value="0"/>
                                                <xs:maxInclusive value="10"/>
                                                <xs:fractionDigits value="2"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="No presentado"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:union>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="15"/>
                                        <xs:maxInclusive value="75"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="comentario" type="xs:string" minOccurs="0"/>
                            <xs:element name="dirección" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="18"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="número" type="xs:integer"/>
                                        <xs:element name="piso" type="xs:string"/>
                                        <xs:element name="población" type="xs:string"/>
                                        <xs:element name="CP">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{5}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dni" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{7,8}[A-Z]{1}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ibq-daw1-1920-27/lmsgi/Unidad_04/Actividad_04_04/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio3.xsd">
    <alumno dni="99887766X">
        <nombre>Dario</nombre>
        <apellidos>Fernández Álvarez</apellidos>
        <nota>3.50</nota>
        <edad>45</edad>
        <comentario>Necesita mejorar</comentario>
        <dirección>
            <calle>Comandante Valles</calle>
            <número>5</número>
            <piso>5D</piso>
            <población>Oviedo</población>
            <CP>33021</CP>
        </dirección>
    </alumno>
    <alumno dni="11223344A">
        <nombre>Luis</nombre>
        <apellidos>Álvarez García</apellidos>
        <nota>6.75</nota>
        <edad>75</edad>
        <comentario>Copió de Dario, Alfredo y Pilar</comentario>
    </alumno>
    <alumno dni="6556677Z">
        <nombre>Pilar</nombre>
        <apellidos>Rodríguez Menéndez</apellidos>
        <nota>8.25</nota>
        <comentario>Copió de todos</comentario>
    </alumno>
    <alumno dni="66554433T">
        <nombre>Alfredo</nombre>
        <apellidos>Martínez González</apellidos>
        <nota>No presentado</nota>
        <edad>42</edad>
        <comentario>Estudió en Universidad de Oviedo</comentario>
        <dirección>
            <calle>Galiana</calle>
            <número>23</número>
            <piso>1C</piso>
            <población>Avilés</población>
            <CP>33400</CP>
        </dirección>
    </alumno>
</alumnos>
